name: karte_flutter

packages:
  - karte_*
  - example

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: flutter analyze .
  
  test:
    run: melos exec --ignore="*example" --ignore=karte_visual_tracking -- flutter test
