name: "Create release branch"
on:
  workflow_dispatch: # Should be executed manually.
jobs:
  create-release:
    runs-on: ubuntu-latest
    # Should be executed on the dev repo.
    if: github.repository != 'plaidev/karte-flutter'
    permissions:
      contents: write
    steps:
      - name: Checkout develop
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: develop
      - name: Configure Git
        run: |
          git config user.email "git@users.noreply.github.com"
          git config user.name "github actions"
          git fetch
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y.%m.%dT%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: Create and push release branch
        run: |
          git checkout -b release/${{ steps.date.outputs.date }}
          git push origin -u release/${{ steps.date.outputs.date }}
      - name: Create Pull Request
        id: create_pr
        env:
          # TODO: Consider using GitHub Apps instead of PAT tokens.
          GH_TOKEN: ${{ secrets.DEV_GH_TOKEN }}
        run: |
          PR_URL=$(gh pr create \
            --title "Release by ${{ github.actor }}" \
            --body "### 以下の項目を確認してください
          - [ ] \`pubspec.yaml\`内のバージョンならびに\`CHANGELOG.md\`が更新されていることを確認した。
          - [ ] サンプルアプリで動作確認を行った。" \
            --base master \
            --head release/${{ steps.date.outputs.date }})
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
      - name: Notify Slack on success
        if: success()
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: |
            ✅ Successfully created release branch
            PR: ${{ steps.create_pr.outputs.pr_url }}
          SLACK_COLOR: success
      - name: Notify Slack on failure
        if: failure()
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: |
            ❌ Failed to create release branch
          SLACK_COLOR: failure
