name: Pull Request Check

on:
  pull_request:

env:
  FLUTTER_VERSION: 3.13.0
  FLUTTER_CHANNEL: 'stable'

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: set up flutter
        uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # v2.21.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: ${{ env.FLUTTER_VERSION }}-${{ env.FLUTTER_CHANNEL }}
      - name: set up melos
        run: |
          flutter pub global activate melos
          ./scripts/setup.sh
      - name: analyze all packages
        run: |
          flutter pub global run melos run analyze
      - name: test all packages
        run: |
          flutter pub global run melos run test
