name: Pull Request Check

on:
  pull_request:

env:
  FLUTTER_VERSION: 3.13.0
  FLUTTER_CHANNEL: 'stable'
  # SHA256 checksum from https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json
  FLUTTER_SHA256: a2fc218708b2eaa395ed108f43fa40242e4c12299730e3e745b966962ada95af

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install flutter
        working-directory: ${{ runner.temp }}
        env:
          FLUTTER_ARCHIVE: flutter_linux_${{ env.FLUTTER_VERSION }}-${{ env.FLUTTER_CHANNEL }}.tar.xz
        run: |
          curl -fsSLO "https://storage.googleapis.com/flutter_infra_release/releases/${FLUTTER_CHANNEL}/linux/${FLUTTER_ARCHIVE}"
          echo "${FLUTTER_SHA256}  ${FLUTTER_ARCHIVE}" | sha256sum -c
          tar xf "${FLUTTER_ARCHIVE}" -C "${HOME}"
          echo "${HOME}/flutter/bin" >> $GITHUB_PATH
      - name: Print Flutter version
        run: flutter --version
      - name: set up melos
        run: |
          echo "${HOME}/.pub-cache/bin" >> $GITHUB_PATH
          flutter pub global activate melos
          ./scripts/setup.sh
      - name: analyze all packages
        run: |
          flutter pub global run melos run analyze
      - name: test all packages
        run: |
          flutter pub global run melos run test
