name: Publish

on:
  pull_request:
    branches: [master]
    types: [closed]

env:
  FLUTTER_VERSION: 3.13.0
  FLUTTER_CHANNEL: 'stable'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: ${{ env.FLUTTER_VERSION }}-${{ env.FLUTTER_CHANNEL }}
      - name: set up melos
        run: |
          flutter pub global activate melos
          ./scripts/setup.sh
      - name: publish dry run
        if: github.event.pull_request.merged == false
        run: |
          melos publish --dry-run -y 2>&1 | grep -e ^Publishing -e '^No unpublished packages found' -e '^\* ' > publish-dry-run.log
      - name: commnet pr
        if: github.event.pull_request.merged == false
        uses: machine-learning-apps/pr-comment@master
        with:
          path: publish-dry-run.log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: publish
        if: github.event.pull_request.merged == true
        run: |
          melos publish --no-dry-run --git-tag-version -y
          git push origin --tags
