name: Tag and start release
on:
  workflow_dispatch:
env:
  FLUTTER_VERSION: 3.13.0
  FLUTTER_CHANNEL: 'stable'
jobs:
  publish-packages:
    name: Create tags for release
    permissions:
      actions: write # Required to trigger release-publish.yml workflow
      contents: write # Required to create and push git tags
    runs-on: ubuntu-latest
    if: github.repository == 'plaidev/karte-flutter'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Setup Flutter
        uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046 # v2.19.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
      - name: Setup Melos
        run: |
          dart pub global activate melos
          dart pub global run melos bootstrap
      - name: Create tags
        # Ref) https://github.com/bluefireteam/melos-action/blob/9bcdb36f9a5556a10467a78aed2cc2e220f54035/action.yml#L118-L122
        run: |
          # We don't care about errors due to creating new tags (`|| true`)
          # since for all packages that didn't get a new release, the tag already exists.
          melos exec -c 1 --no-private -- git tag \$MELOS_PACKAGE_NAME-v\$MELOS_PACKAGE_VERSION || true
          git push --tags
      - name: Start release
        # Ref) https://github.com/bluefireteam/melos-action/blob/9bcdb36f9a5556a10467a78aed2cc2e220f54035/examples/01-workflow-dispatch/release-tag.yml#L22-L25
        run: |
          melos exec -c 1 --no-published --no-private --order-dependents -- \
          gh workflow run release-publish.yml \
          --ref \$MELOS_PACKAGE_NAME-v\$MELOS_PACKAGE_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify Slack on success
        if: success()
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: 'Release tagging workflow completed successfully'
          SLACK_COLOR: success
      - name: Notify Slack on failure
        if: failure()
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: 'Release tagging workflow failed'
          SLACK_COLOR: failure
