name: Build Android app with old environment
on:
  # TODO: Enable to run automatically before release.
  workflow_dispatch:
env:
  # NOTE: Refer to each module's pubspec.yaml (e.g. karte_core/pubspec.yaml) for minimum SDK version.
  FLUTTER_VERSION: '3.7.0'
  FLUTTER_CHANNEL: 'stable'
  JAVA_VERSION: '11'
jobs:
  build-android:
    name: Build Android app with old environment
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Flutter
        uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # v2.21.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
      - name: Get dependencies
        working-directory: build_tests/old_app_test
        run: flutter pub get
      - name: Build APK
        working-directory: build_tests/old_app_test
        run: flutter build apk --release
