name: Build Android app with old environment
on:
  # TODO: Enable to run automatically before release.
  workflow_dispatch:
env:
  # NOTE: Refer to each module's pubspec.yaml (e.g. karte_core/pubspec.yaml) for minimum SDK version.
  FLUTTER_VERSION: '3.7.0'
  FLUTTER_CHANNEL: 'stable'
  # SHA256 checksum from https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json
  FLUTTER_SHA256: 51160abac1d0d82b45647be6b2a6ed2d3827d51c3920f2c8ebf3ea8cebe6f484
  JAVA_VERSION: '11'
jobs:
  build-android:
    name: Build Android app with old environment
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Install Flutter
        working-directory: ${{ runner.temp }}
        env:
          FLUTTER_ARCHIVE: flutter_linux_${{ env.FLUTTER_VERSION }}-${{ env.FLUTTER_CHANNEL }}.tar.xz
        run: |
          curl -fsSLO "https://storage.googleapis.com/flutter_infra_release/releases/${FLUTTER_CHANNEL}/linux/${FLUTTER_ARCHIVE}"
          echo "${FLUTTER_SHA256}  ${FLUTTER_ARCHIVE}" | sha256sum -c
          tar xf "${FLUTTER_ARCHIVE}" -C "${HOME}"
          echo "${HOME}/flutter/bin" >> $GITHUB_PATH
      - name: Print Flutter version
        run: flutter --version
      - name: Get dependencies
        working-directory: build_tests/old_app_test
        run: flutter pub get
      - name: Build APK
        working-directory: build_tests/old_app_test
        run: flutter build apk --release
